### ISSUE TITLE
Abfrage nach dem latest event in der Datenbank optimieren [EVENTS]

### ISSUE THREAD

**Issue by ChrisMalewski** [52North/wv-eventing-rest-api#1]
Anfragedauer min 12 Sek.

- Vorschlag 1: Erzeuge „Redundanz“ in der Tabelle event_log_mail durch das mehrfache Hinzufügen eines Timeseries-too-old Events, nämlich je subscription / notification
- Vorschlag 2: Speichere das latestEvent einer Notificaiton als attribut la-test_event_pkid in Notification, analog zur Dataset REST API. Hierdurch wird das attribut Subscription in event_log_mail obsolet. Hierdurch wird auch der endpunkt event?latest=true obsolet 
- Vorschlag 3: Abfrage der letzten Events über DB-Funktion (get_notification_last_event_log_id())

**Comment by matthesrieke** [comment]
Ansatz: zunächst Option 3 austesten

**Comment by matthesrieke** [comment]
Die Optimierung der Events-Ressource hat auch signifikante Performance-Verbesserungen ergeben (~2 Sekunden in meiner Entwicklungsumgebung). Ich würde vorschlagen, den Test in eurer Umgebung noch einmal durchzuführen und die Performance zu evaluieren.

**Comment by che-** [comment]
http://192.168.101.105/eventing-rest-api/v1/events
-> Laufzeit ca. 2,56 Sekunden bei 17.002 Events gesamt

http://192.168.101.105/eventing-rest-api/v1/events?latest=true
-> Laufzeit ca. 20,48 Sekunden bei 63 Events gesamt

Laufzeit für Latest Events ist nach wie vor deutlich zu lang!

**Comment by che-** [comment]
![laufzeit_latest_events_](https://user-images.githubusercontent.com/5013309/42759688-5f71961a-88f7-11e8-80a0-b2b302abbfaa.PNG)

**Comment by ChrisMalewski** [comment]
Abfragezeit bei 63 latest events insgesamt.

![grafik](https://user-images.githubusercontent.com/871131/42815258-3316c312-89c7-11e8-9069-07e37790bef7.png)

**Comment by CarstenHollmann** [comment]
Ich habe das nachstellen können. So wie es aussieht, ist die Optimierung von Matthes für die Latest-Abfrage nach der Umstellung auf die Nutzung des Views wirkungslos geworden (durch die Anfragestrategie musste der View mehrfach aufgebaut werden). Ich habe einen Weg gefunden und werde das darüber lösen, dass für die Latest-Abfrage eine andere Strategie verwendet wird. Nach einem ersten Test benötigt die Abfrage in meiner Umgebung ca. 2,8 sek. Ich werde das entsprechend umsetzen.

**Comment by ChrisMalewski** [comment]
In unserem Test benötigt die Abfrage 3.2 Sekunden bei 70 latest Events.
