### ISSUE TITLE
Wenn label in subscription nicht in DB steht -> nicht weglassen sondern "" [TEMPLATES]

### ISSUE THREAD

**Issue by ChrisMalewski** [52North/wv-eventing-rest-api#11]
-	Wenn kein Primary rule vorhanden, dann wird von der DB kein label gene-riert. Bitte in der Ergebnismenge label: „“ ausgeben und nicht label ganz weg lassen.

**Comment by matthesrieke** [comment]
Prüfen, ob JSON encoder es erlaubt, NULL-Objekte ausgeben kann (per Konfiguration).

**Comment by matthesrieke** [comment]
@ChrisMalewski es war bisher nach meiner Recherche nie ein "label" (oder "description") für die `/subscriptions`- Ressource vorgesehen. Das DB-Schema sieht auch für Subscriptions keine Labels vor. Wie soll hier vorgegangen werden? Soll das Label der Primary Rule genutzt werden?

**Comment by ChrisMalewski** [comment]
@matthesrieke 
Das ist richtig. Dieses Issue ist falsch getaggt. Es geht um das Label in der Template/Notification Ressource. 
Hier nimmst du schon das Label der Primary rule. Wenn das label allerdings leer ist bzw. keine primary Rule gesetzt ist, soll "label": null gesetzt werden.
Entschuldige die Verwirrung.

**Comment by matthesrieke** [comment]
die serialisierung als NULL-Wert (per Konfiguration der JSON-Komponente) hat einige Seiteneffekte auf andere Ressourcen. Ich habe das Label jetzt auf einen leeren String gesetzt, falls nicht befüllbar.
