### ISSUE TITLE
[BUG] Im Admin-Fall fehlt das Attribut „admin=true“ [USERS]

### ISSUE THREAD

**Issue by ChrisMalewski** [52North/wv-eventing-rest-api#13]
-	[BUG] Es wird im Admin-Fall nicht „admin=true“ gesetzt. Allerdings kann nicht 100%ig verifiziert werden, ob ein Nutzer ein Admin ist, da noch die Dokumentation zur Konfiguration fehlt. Bitte letztere ergänzen.

**Comment by ChrisMalewski** [comment]
Funktioniert technisch
Bitte in der Doku unter 2.3.2 ergänzen:
Soll ein Nutzer Admin einer Gruppe sein, so muss er sowohl Mitglied in der User-Gruppe als auch in der Admin-Gruppe sein.

**Comment by CarstenHollmann** [comment]
Wir haben deinen Text-Vorschlag in das Dokument integriert.

**Comment by ChrisMalewski** [comment]
Hallo Carsten: Bitte die Doku unter 2.3.2 Absatz 2 wie folgt ändern: 

Die Eigenschaft groupPrefix definiert einen Präfix, der Gruppennamen voran gestellt sein muss. Ist
dies für eine Gruppe nicht der Fall, wird sie in der API nicht berücksichtigt. Der Wert adminSuffix
definiert die Administrationsgruppe zu einer bestehenden Nutzergruppe. Z.B. ist nach oben
stehender Konfiguration die Gruppe sensorweb-opladen-admins die Administrationsgruppe zu der Nutzergruppe sensorweb-opladen: Mitglieder der Administrationsgruppe können die Gruppen-Abonnements verwalten. Soll ein Nutzer Gruppenadmin der Gruppe sensorweb-opladen sein, so muss er sowohl Mitglied in dieser Nutzergruppe (sensorweb-opladen) als auch in der dazugehörigen Admin-Gruppe (sensorweb-opladen-admins) sein.

**Comment by ChrisMalewski** [comment]
Nach Änderung bitte schließen.

**Comment by matthesrieke** [comment]
Der Absatz ist entsprechend in der Doku angepasst.
