### ISSUE TITLE
Template JSON Objekt unvollständig [TEMPLATES]

### ISSUE THREAD

**Issue by ChrisMalewski** [52North/wv-eventing-rest-api#15]
o	Bei templates?expanded=true

- [BUG] notificationLevel einer rule hat kein label
- [BUG] die checkAge Regeln fehlen ganz
- [BUGs] bei Eventing aktiviert/deaktiviert

•	eventTrigger label bei 312 anpassen auf Eventing deak-tiviert
•	Eventing aktiviert/deaktiviert ist eventType 2: "Das Ereig-nis wurde duch die Aenderung eines Attributes einer Zeitreihe erzeugt"
•	Regelblock unvollständig
o	notificationLevel fehlt
o	id 
o	href

**Comment by che-** [comment]
Die checkAge Regeln fehlen immer noch.
