### ISSUE TITLE
[BUG] Konsistenz beim Paging

### ISSUE THREAD

**Issue by ChrisMalewski** [52North/wv-eventing-rest-api#2]
Es werden nicht alle Endpunkte mit Paging ausgeliefert. (z.B. eventtypes, notofcationLevel, eventTriggers)

**Comment by matthesrieke** [comment]
Entscheidung: Paging auch hier einführen und normale Page-Größen berücksichtigen.

**Comment by ChrisMalewski** [comment]
OK.
