### ISSUE TITLE
Bei den Check-Age Events und Ein-/Ausgeschaltet Events wird kein Subscription-Verweis in der JSON-Reponse angegeben. [/EVENTS]]

### ISSUE THREAD

**Issue by ChrisMalewski** [52North/wv-eventing-rest-api#27]
![grafik](https://user-images.githubusercontent.com/871131/42819626-66ce9f1a-89d4-11e8-86aa-7e08201afc4e.png)

**Comment by CarstenHollmann** [comment]
Hierzu habe ich noch eine Frage: Die Check-Age und Eingeschaltet/Ausgeschaltet Events sind allgemeiner und können zu mehreren Subscriptions eines Nutzers gehören (z.B. es gibt zwei Subscriptions die unterschiedliche Wasserstandsgrenzwerte am selben Pegel überwachen). Für beide Subscriptions werden dann die Check-Age und Ein/Aus Events überwacht. Daher gibt es zwei Optionen wie das dargestellt werden kann:

A) Alle Subscriptions des Nutzers, die zu den Check-Age und Ein/Aus-Events gehören als Array im JSON auflisten

B) Die Events mehrfach auflisten mit den jeweils unterschiedlichen zugehörigen Subscription-Referenzen

A wäre ggf. sauberer, aber wir sollten das noch einmal besprechen.

**Comment by simonjirka** [comment]
Option B umsetzen.
