### ISSUE TITLE
[BUG] Paging funktioniert nicht

### ISSUE THREAD

**Issue by ChrisMalewski** [52North/wv-eventing-rest-api#3]
Getestet wurden subscriptions und events:
http://192.168.101.105/eventing-rest-api/v1/events?latest=true&offset=65&limit=10

**Comment by ChrisMalewski** [comment]
Paging funktioniert nach wie vor nicht. 
Getestet
http://192.168.101.105/eventing-rest-api/v1/events?latest=true&offset=40&limit=10 	
-> Ausgabe von mehr als 10 Events.

**Comment by matthesrieke** [comment]
Hi Christian,

aufgrund der Spezialfunktion bei `latest=true` (mehere Queries werden in Java zu einem Ergebnis verbunden) ist hier kein Paging unterstützt. Falls das jedoch gewünscht ist, müssten wir hierfür ein Paging auf Java-Ebene etablieren.

Das Paging ohne "latest" sollte jedoch soweit funktionieren.

**Comment by ChrisMalewski** [comment]
Hi Matthes,
danke, das paging ohne "latest" funktioniert, sehr schön! Wir stecken nochmal die Köpfe zusammen und definieren, was in dem latest=true Fall erwartet wird.

**Comment by che-** [comment]
Bei folgenden Endpunkten funktioniert das Paging nicht:

http://192.168.101.105/eventing-rest-api/v1/eventTriggers?offset=0&limit=5
http://192.168.101.105/eventing-rest-api/v1/eventTypes?offset=0&limit=2
http://192.168.101.105/eventing-rest-api/v1/notificationLevels?limit=2

**Comment by ChrisMalewski** [comment]
Bitte paging im latest=true Fall ergänzen sowie auf den von che genannten Endpunkten realisieren.
Auf den nächsten Meilenstein verschieben.
