### ISSUE TITLE
[DOKU] GroupIds fehlt in der Doku [SUBSCRIPTIONS]

### ISSUE THREAD

**Issue by ChrisMalewski** [52North/wv-eventing-rest-api#9]

**Comment by matthesrieke** [comment]
Hier war ich mir nicht ganz sicher, was die Problematik war. In der gegenwärtigen Doku konnt ich keine Verweise auf die GroupID finden (die API-Dokumentation deckt momentan insbesondere noch nicht das zurückgegebene Datenmodell ab)

**Comment by CarstenHollmann** [comment]
Wir haben den Group Filter-Parameter in die Doku hinzugefügt.
